import math
import numpy as np
import magnum as mn
import habitat_sim
from typing import Any, Optional, Dict

from src.sensors.base_sensor import BaseSensor
from src.datatypes.image import RGBImage, DepthMap, SemanticMap, InstanceMap
from src.datatypes.motion_state import MotionState
from src.detections.obb import global_obbs
from src.detections.bbox2d import boxes_from_maps
from src.detections.bbox3d import obbs_for_visible
from src.sensors.camera.models import (
    Camera,
    PerspectiveCamera,
    OpenCVFisheyeCamera,
    ThinPrismFisheyeCamera,
    OmnidirectionalCamera,
    DoubleSphereCamera,
    EquirectangularCamera,
)
from src.sensors.camera.remap import transition_camera_view
from src.sensors.registry import register_sensor
from src.utils.geometry import (
    compose_pose,
    quaternion_to_habitat_euler,
    rotate_vectors,
)


# RGB camera models that habitat-sim can rasterize natively (no remap needed).
_HABITAT_NATIVE_RGB = {"pinhole", "equirectangular", "orthographic"}
# Models treated as a perspective/pinhole pipeline (planar z-depth default).
_PINHOLE_LIKE = {"pinhole", "perspective"}


def _as_builtin(value):
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, tuple):
        return [_as_builtin(v) for v in value]
    if isinstance(value, list):
        return [_as_builtin(v) for v in value]
    if isinstance(value, dict):
        return {str(k): _as_builtin(v) for k, v in value.items()}
    if isinstance(value, np.generic):
        return value.item()
    return value


@register_sensor("camera")
class CameraSensor(BaseSensor):
    """
    Camera sensor supporting arbitrary projection models for SLAM data generation.

    Design (see project plan):
    - **RGB** keeps habitat-sim's rasterization. ``pinhole``/``equirectangular``/
      ``orthographic`` render natively; any other model is rendered as a large
      equirectangular image and then **remapped** to the target model.
    - **Depth / Semantic** are generated by per-pixel **ray casting**
      (``sim.cast_ray``) through the target camera model's rays, which is more
      accurate than rasterization and works for any (wide-FOV) model.

    The projection math comes from the vendored spatialkit camera models
    (``src/sensors/camera/models``). Camera-specific generation stays inside
    this class; SensorSuite wraps returned output payloads for export.
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # BaseSensor stores the declared outputs as ``self.outputs``
        # (lowercased name -> params); the camera reads them by modality name.
        self.modalities = set(self.outputs)
        self.modality_params = self.outputs
        parameters = self.parameters
        self.model = parameters.get("model", "pinhole").lower()
        self.width = int(parameters.get("width", 640))
        self.height = int(parameters.get("height", 480))
        if "hfov" in parameters:
            self.hfov = float(parameters["hfov"])
        elif "intrinsic" in parameters:
            intrinsic = parameters["intrinsic"]
            if not isinstance(intrinsic, (list, tuple)) or len(intrinsic) != 4:
                raise ValueError("camera intrinsic must be [fx, fy, cx, cy].")
            fx = float(intrinsic[0])
            self.hfov = math.degrees(2.0 * math.atan(self.width / (2.0 * fx)))
        else:
            self.hfov = 90.0
        self.min_distance = float(parameters.get("min_distance", 0.05))
        self.max_distance = float(parameters.get("max_distance", 100.0))
        self._raycast_outputs = self.modalities & {
            "depth", "semantic", "instance", "bbox2d", "bbox3d"
        }

        # Resolve static offset pose from base_link to this sensor's parent_link.
        # No silent fallback: an unresolvable parent_link is a config error, not
        # a recoverable one -- masking it here would silently mount the sensor
        # at identity and produce plausible-looking but wrong ground truth.
        self.pose = self.tf_manager.get_relative_pose("base_link", self.parent_link)

        # Depth representation: pinhole-like -> planar z-depth, wide-angle -> euclidean.
        default_depth = "planar" if self.model in _PINHOLE_LIKE else "euclidean"
        depth_cfg = self.modality_params.get("depth", {})
        self.depth_type = depth_cfg.get(
            "depth_type", parameters.get("depth_type", default_depth)
        ).lower()

        # Target projection model (spatialkit Camera). Needed for ray casting
        # (depth/semantic) and for RGB remap (non-native models).
        self.cam: Optional[Camera] = None
        self.needs_remap = False
        self.src_cam: Optional[EquirectangularCamera] = None

        if self._raycast_outputs:
            self.cam = self._build_model()
            self._precompute_rays()
        if self._has_output("rgb") and self.model not in _HABITAT_NATIVE_RGB:
            # RGB with a non-native model: render equirect, then remap.
            if self.cam is None:
                self.cam = self._build_model()
            self.needs_remap = True
            self.render_height = int(parameters.get("render_height", 1024))
            self.render_width = self.render_height * 2
            self.src_cam = EquirectangularCamera.from_image_size(
                [self.render_width, self.render_height]
            )
        # Detection context is read from the shared Scene (self.scene.categories /
        # .model), populated when the Scene is bound to the sim. Per-instance world
        # OBBs are memoized here on first bbox3d use.
        self._world_obbs = None

    @classmethod
    def validate_outputs(cls, outputs: Dict[str, Any]) -> None:
        allowed = {"rgb", "depth", "semantic", "instance", "bbox2d", "bbox3d"}
        unsupported = sorted(set(outputs) - allowed)
        if unsupported:
            raise ValueError(
                "camera outputs contain unsupported name(s): "
                f"{', '.join(unsupported)}. Available: {', '.join(sorted(allowed))}."
            )

    def _has_output(self, output_name: str) -> bool:
        return output_name in self.modalities

    # ------------------------------------------------------------------
    # Model construction
    # ------------------------------------------------------------------
    def _build_model(self) -> Camera:
        """Builds the target spatialkit Camera from this sensor's parameters."""
        p = self.parameters
        image_size = [self.width, self.height]

        if self.model in _PINHOLE_LIKE:
            if "intrinsic" in p:
                intrinsic = p["intrinsic"]
                if not isinstance(intrinsic, (list, tuple)) or len(intrinsic) != 4:
                    raise ValueError("camera intrinsic must be [fx, fy, cx, cy].")
                fx, fy, cx, cy = [float(v) for v in intrinsic]
                cam_dict = {
                    "image_size": image_size,
                    "focal_length": (fx, fy),
                    "principal_point": (cx, cy),
                    "skew": p.get("skew", 0.0),
                    "radial": p.get("radial", [0.0, 0.0, 0.0]),
                    "tangential": p.get("tangential", [0.0, 0.0]),
                }
                return PerspectiveCamera(cam_dict)
            if "focal_length" in p and "principal_point" in p:
                cam_dict = {
                    "image_size": image_size,
                    "focal_length": tuple(p["focal_length"]),
                    "principal_point": tuple(p["principal_point"]),
                    "skew": p.get("skew", 0.0),
                    "radial": p.get("radial", [0.0, 0.0, 0.0]),
                    "tangential": p.get("tangential", [0.0, 0.0]),
                }
                return PerspectiveCamera(cam_dict)
            # Derive square-pixel intrinsics from horizontal FOV.
            fx = self.width / (2.0 * math.tan(math.radians(self.hfov) / 2.0))
            cam_dict = {
                "image_size": image_size,
                "focal_length": (fx, fx),
                "principal_point": ((self.width - 1) / 2.0, (self.height - 1) / 2.0),
                "skew": 0.0,
                "radial": p.get("radial", [0.0, 0.0, 0.0]),
                "tangential": p.get("tangential", [0.0, 0.0]),
            }
            return PerspectiveCamera(cam_dict)

        if self.model == "opencv_fisheye":
            return OpenCVFisheyeCamera(
                {
                    "image_size": image_size,
                    "focal_length": tuple(p["focal_length"]),
                    "principal_point": tuple(p["principal_point"]),
                    "skew": p.get("skew", 0.0),
                    "radial": p["radial"],  # [k1,k2,k3,k4]
                }
            )

        if self.model == "thinprism":
            return ThinPrismFisheyeCamera(
                {
                    "image_size": image_size,
                    "focal_length": tuple(p["focal_length"]),
                    "principal_point": tuple(p["principal_point"]),
                    "radial": p["radial"],  # [k1,k2,k3,k4]
                    "tangential": p["tangential"],  # [p1,p2]
                    "prism": p["prism"],  # [sx1,sy1]
                }
            )

        if self.model == "doublesphere":
            return DoubleSphereCamera(
                {
                    "image_size": image_size,
                    "focal_length": tuple(p["focal_length"]),
                    "principal_point": tuple(p["principal_point"]),
                    "xi": p["xi"],
                    "alpha": p["alpha"],
                    "fov_deg": p.get("fov_deg", 180.0),
                }
            )

        if self.model == "omnidirect":
            return OmnidirectionalCamera(
                {
                    "image_size": image_size,
                    "distortion_center": tuple(p["distortion_center"]),
                    "poly_coeffs": p["poly_coeffs"],
                    "inv_poly_coeffs": p["inv_poly_coeffs"],
                    "affine": p.get("affine", [1.0, 0.0, 0.0]),
                    "fov_deg": p.get("fov_deg", 180.0),
                }
            )

        if self.model in ("equirect", "equirectangular"):
            return EquirectangularCamera(
                {
                    "image_size": image_size,
                    "min_phi_deg": p.get("min_phi_deg", -90.0),
                    "max_phi_deg": p.get("max_phi_deg", 90.0),
                }
            )

        raise ValueError(
            f"[CameraSensor:{self.name}] Unsupported camera model '{self.model}'."
        )

    def _precompute_rays(self) -> None:
        """
        Precompute per-pixel ray directions in the **habitat sensor frame** for
        ray casting, plus helpers for depth conversion and validity.

        spatialkit cameras use the CV convention (+Z forward, +X right, +Y down).
        Habitat sensors use the GL convention (-Z forward, +X right, +Y up), so we
        flip Y and Z: R = diag(1, -1, -1).
        """
        rays_cv, valid = self.cam.convert_to_rays(z_fixed=False)  # (3, H*W) unit rays
        rays_hab = rays_cv.copy()
        rays_hab[1, :] *= -1.0  # Y: down -> up
        rays_hab[2, :] *= -1.0  # Z: forward -> -Z

        self._ray_dirs_local = rays_hab.T.astype(np.float64)  # (H*W, 3), habitat frame
        self._ray_valid = np.asarray(valid).reshape(-1)
        # Cosine to optical axis (CV +Z) for planar z-depth conversion.
        self._ray_cos = rays_cv[2, :].astype(np.float64)

    def calibration_dict(self) -> Dict[str, Any]:
        """
        Returns a sidecar-friendly calibration record for this camera.

        The project supports projection models that do not map cleanly onto
        ROS ``sensor_msgs/CameraInfo`` fields, so calibration is exported as
        structured YAML beside the MCAP rather than as a lossy ROS channel.
        """
        cam = self.cam
        if cam is None and self.model != "orthographic":
            cam = self._build_model()

        model_data = cam.export_cam_dict() if cam is not None else {
            "cam_type": self.model.upper(),
            "image_size": [self.width, self.height],
        }
        return _as_builtin({
            "name": self.name,
            "frame_id": self.parent_link,
            "model": self.model,
            "width": self.width,
            "height": self.height,
            "hfov": self.hfov,
            "min_distance": self.min_distance,
            "max_distance": self.max_distance,
            "depth_type": self.depth_type,
            "enabled_outputs": sorted(self.modalities),
            "camera_model": model_data,
            "parameters": self.parameters,
        })

    # ------------------------------------------------------------------
    # BaseSensor interface
    # ------------------------------------------------------------------
    def is_native(self) -> bool:
        # RGB is rasterized by habitat (directly or via an equirect render source).
        # Depth/Semantic/Instance are ray-cast and therefore non-native.
        return self._has_output("rgb")

    def get_sensor_spec(self) -> Optional[habitat_sim.SensorSpec]:
        """SensorSpec for native rendering. Returns None without an RGB output."""
        if not self._has_output("rgb"):
            return None

        if self.needs_remap:
            # Render a large equirectangular source; get_observation remaps it.
            # Equirectangular requires habitat's dedicated spec class -- a
            # CameraSensorSpec with the EQUIRECTANGULAR subtype is rejected by the
            # simulator ("specification is null").
            spec = habitat_sim.EquirectangularSensorSpec()
            spec.resolution = [self.render_height, self.render_width]
        elif self.model == "equirectangular":
            spec = habitat_sim.EquirectangularSensorSpec()
            spec.resolution = [self.height, self.width]
        else:
            spec = habitat_sim.CameraSensorSpec()
            spec.sensor_subtype = (
                habitat_sim.SensorSubType.ORTHOGRAPHIC
                if self.model == "orthographic"
                else habitat_sim.SensorSubType.PINHOLE
            )
            spec.resolution = [self.height, self.width]
            spec.hfov = mn.Deg(self.hfov)

        spec.uuid = self.name
        spec.sensor_type = habitat_sim.SensorType.COLOR
        p = self.pose.position
        spec.position = mn.Vector3(float(p[0]), float(p[1]), float(p[2]))
        spec.orientation = mn.Vector3(*quaternion_to_habitat_euler(self.pose.orientation))
        return spec

    def get_observation(
        self,
        sim: habitat_sim.Simulator,
        motion_state: MotionState,
    ) -> Dict[str, Any]:
        """
        Returns output payloads keyed by configured camera output name:
        - RGB: rasterized image (native, or remapped from equirect).
        - Depth: float32 (H, W) planar z-depth or euclidean range.
        - Semantic: (H, W) hit semantic_id (Class ID).
        - Instance: (H, W) hit object_id (Instance ID).
        """
        outputs: Dict[str, Any] = {}
        if self._has_output("rgb"):
            outputs["rgb"] = self._observe_rgb(sim)
        if self._raycast_outputs:
            outputs.update(self._observe_raycast(sim, motion_state))
        return outputs

    # ------------------------------------------------------------------
    # RGB
    # ------------------------------------------------------------------
    def _observe_rgb(self, sim: habitat_sim.Simulator) -> RGBImage:
        obs = sim.get_sensor_observations()
        if self.name not in obs:
            return RGBImage(np.empty((0, 0), dtype=np.uint8))
        image = obs[self.name]
        if not self.needs_remap:
            return RGBImage(image)
        # Remap the equirectangular render to the target camera model.
        return RGBImage(transition_camera_view(image, self.src_cam, self.cam))

    # ------------------------------------------------------------------
    # Ray casting (depth / semantic / instance, and reused by detections)
    # ------------------------------------------------------------------
    def world_pose(self, motion_state: MotionState):
        """This camera's world pose at ``motion_state`` -> (position xyz, quat xyzw).

        position = agent_pos + R(agent) * mount_offset; orientation = R(agent) * R(offset).
        """
        agent_pos = np.asarray(motion_state.position, dtype=np.float64)
        q_agent_xyzw = np.asarray(motion_state.orientation, dtype=np.float64)
        sensor_pos_global, q_sensor_global_xyzw = compose_pose(
            agent_pos,
            q_agent_xyzw,
            self.pose.position,
            self.pose.orientation,
        )
        return sensor_pos_global, q_sensor_global_xyzw

    def _cast(self, sim: habitat_sim.Simulator, motion_state: MotionState):
        """Ray-cast the scene from this camera. Returns ``(RaycastResult, hit_mask[H*W])``."""
        if self.scene is None:
            raise RuntimeError("Camera raycast outputs require a Scene; no sim.cast_ray fallback is created.")

        sensor_pos_global, q_sensor_global_xyzw = self.world_pose(motion_state)

        # Rotate all local rays into the world frame; give invalid pixels (outside the
        # model FOV) a placeholder direction so the batch is well-defined (masked out).
        dirs = rotate_vectors(self._ray_dirs_local, q_sensor_global_xyzw).copy()
        invalid = ~self._ray_valid
        if np.any(invalid):
            dirs[invalid] = (0.0, 0.0, -1.0)

        # The Scene is bound/synced once per capture by SensorSuite.observe;
        # the backend raises if queried unbound.
        origins = np.broadcast_to(sensor_pos_global, dirs.shape)
        res = self.scene.cast_rays(
            origins, dirs,
            min_distance=self.min_distance,
            max_distance=self.max_distance,
        )
        return res, (res.hit & self._ray_valid)

    def cast_ids(
        self, sim: habitat_sim.Simulator, motion_state: MotionState
    ) -> tuple[InstanceMap, SemanticMap]:
        """One ray cast -> ``(object_id_map, semantic_id_map)``, both (H, W) uint32; 0 = no hit."""
        res, hit = self._cast(sim, motion_state)
        obj = np.where(hit, res.object_id, 0).astype(np.uint32).reshape(self.height, self.width)
        sem = np.where(hit, res.semantic_id, 0).astype(np.uint32).reshape(self.height, self.width)
        return InstanceMap(obj), SemanticMap(sem)

    def _ensure_detection_context(self, sim: habitat_sim.Simulator) -> None:
        categories = self.scene.categories
        if categories is None:
            raise RuntimeError(
                f"Camera '{self.name}' produces detections but the shared Scene "
                "has no category table; it must be bound to the sim (e.g. by "
                "create_simulator) before capture."
            )
        if self._world_obbs is None and self._has_output("bbox3d"):
            # Reuse the SceneModel the Scene already built in bind() (item 5);
            # only extract from scratch for backends that hold no model (e.g. sim).
            scene_model = self.scene.model
            if scene_model is None:
                from src.raycasting import extract_scene_model

                scene_model = extract_scene_model(sim, self.scene.geometry)
            self._world_obbs = global_obbs(scene_model, categories)

    def _bbox2d_min_box_px(self) -> int:
        det2d_cfg = self.modality_params.get("bbox2d", {})
        return int(det2d_cfg.get("min_box_px", self.parameters.get("min_box_px", 8)))

    def _observe_raycast(
        self, sim: habitat_sim.Simulator, motion_state: MotionState
    ) -> Dict[str, Any]:
        H, W = self.height, self.width
        res, hit = self._cast(sim, motion_state)
        outputs: Dict[str, Any] = {}
        obj = None
        sem = None

        if self._has_output("depth"):
            dist = np.where(hit, res.distance, 0.0).astype(np.float32)
            if self.depth_type == "planar":
                dist = (dist * self._ray_cos).astype(np.float32)
            outputs["depth"] = DepthMap(dist.reshape(H, W))

        needs_semantic = self._has_output("semantic") or self._has_output("bbox2d")
        if needs_semantic:
            sem = np.where(hit, res.semantic_id, 0).astype(np.uint32).reshape(H, W)

        needs_instance = (
            self._has_output("instance")
            or self._has_output("bbox2d")
            or self._has_output("bbox3d")
        )
        if needs_instance:
            obj = np.where(hit, res.object_id, 0).astype(np.uint32).reshape(H, W)

        if self._has_output("semantic"):
            if sem is None:
                sem = np.where(hit, res.semantic_id, 0).astype(np.uint32).reshape(H, W)
            outputs["semantic"] = SemanticMap(sem)

        if self._has_output("instance"):
            if obj is None:
                obj = np.where(hit, res.object_id, 0).astype(np.uint32).reshape(H, W)
            outputs["instance"] = InstanceMap(obj)

        if self._has_output("bbox2d"):
            if sem is None:
                sem = np.where(hit, res.semantic_id, 0).astype(np.uint32).reshape(H, W)
            if obj is None:
                obj = np.where(hit, res.object_id, 0).astype(np.uint32).reshape(H, W)
            self._ensure_detection_context(sim)
            outputs["bbox2d"] = boxes_from_maps(
                obj, sem, self.scene.categories, self._bbox2d_min_box_px()
            )

        if self._has_output("bbox3d"):
            if obj is None:
                obj = np.where(hit, res.object_id, 0).astype(np.uint32).reshape(H, W)
            self._ensure_detection_context(sim)
            cam_pos, cam_quat = self.world_pose(motion_state)
            outputs["bbox3d"] = obbs_for_visible(
                obj, self._world_obbs, cam_pos, cam_quat
            )

        return outputs
