import math
import numpy as np
import magnum as mn
import habitat_sim
from typing import Any, Optional, Dict

from src.sensors.base_sensor import BaseSensor
from src.datatypes.pose import Pose3D
from src.datatypes.motion_state import MotionState
from src.sensors.camera.models import (
    Camera,
    PerspectiveCamera,
    OpenCVFisheyeCamera,
    ThinPrismFisheyeCamera,
    OmnidirectionalCamera,
    DoubleSphereCamera,
    EquirectangularCamera,
)
from src.sensors.camera.remap import transition_camera_view
from src.sensors.registry import register_sensor


# RGB camera models that habitat-sim can rasterize natively (no remap needed).
_HABITAT_NATIVE_RGB = {"pinhole", "equirectangular", "orthographic"}
# Models treated as a perspective/pinhole pipeline (planar z-depth default).
_PINHOLE_LIKE = {"pinhole", "perspective"}


@register_sensor("camera")
class CameraSensor(BaseSensor):
    """
    Camera sensor supporting arbitrary projection models for SLAM data generation.

    Design (see project plan):
    - **RGB** keeps habitat-sim's rasterization. ``pinhole``/``equirectangular``/
      ``orthographic`` render natively; any other model is rendered as a large
      equirectangular image and then **remapped** to the target model.
    - **Depth / Semantic** are generated by per-pixel **ray casting**
      (``sim.cast_ray``) through the target camera model's rays, which is more
      accurate than rasterization and works for any (wide-FOV) model.

    The projection math comes from the vendored spatialkit camera models
    (``src/sensors/camera/models``). Public interface (constructor signature,
    ``is_native``/``get_sensor_spec``/``get_observation`` and the
    ``{name: image}`` return contract) is preserved so the rest of the pipeline
    (SensorSuite, simulator factory, export_helper) is untouched.
    """

    def __init__(
        self,
        name: str,
        sensor_type: str,
        parent_link: str,
        hz: int,
        topic: str,
        schema: str,
        parameters: dict,
        tf_manager: Any,
    ):
        super().__init__(
            name=name,
            sensor_type=sensor_type,
            parent_link=parent_link,
            hz=hz,
            topic=topic,
            schema=schema,
            parameters=parameters,
            tf_manager=tf_manager,
        )

        self.modality = parameters.get("modality", "rgb").lower()
        self.model = parameters.get("model", "pinhole").lower()
        self.width = int(parameters.get("width", 640))
        self.height = int(parameters.get("height", 480))
        self.hfov = float(parameters.get("hfov", 90.0))
        self.min_distance = float(parameters.get("min_distance", 0.05))
        self.max_distance = float(parameters.get("max_distance", 100.0))

        # Resolve static offset pose from base_link to this sensor's parent_link.
        base_link = "base_link"
        try:
            self.pose = tf_manager.get_relative_pose(base_link, parent_link)
        except Exception:
            self.pose = Pose3D(np.zeros(3), np.array([0.0, 0.0, 0.0, 1.0]))

        self.position = mn.Vector3(
            self.pose.position[0], self.pose.position[1], self.pose.position[2]
        )
        # Euler (pitch, yaw, roll) for the native habitat SensorSpec.
        self.euler = self._quaternion_to_euler(self.pose.orientation)
        # Offset quaternion for ray-cast world composition (matches IdealLiDAR3D).
        q = self.pose.orientation
        self.orientation = mn.Quaternion(mn.Vector3(q[0], q[1], q[2]), q[3])

        # Depth representation: pinhole-like -> planar z-depth, wide-angle -> euclidean.
        default_depth = "planar" if self.model in _PINHOLE_LIKE else "euclidean"
        self.depth_type = parameters.get("depth_type", default_depth).lower()

        # Target projection model (spatialkit Camera). Needed for ray casting
        # (depth/semantic) and for RGB remap (non-native models).
        self.cam: Optional[Camera] = None
        self.needs_remap = False
        self.src_cam: Optional[EquirectangularCamera] = None

        if self.modality in ("depth", "semantic"):
            self.cam = self._build_model()
            self._precompute_rays()
        elif self.modality == "rgb" and self.model not in _HABITAT_NATIVE_RGB:
            # RGB with a non-native model: render equirect, then remap.
            self.cam = self._build_model()
            self.needs_remap = True
            self.render_height = int(parameters.get("render_height", 1024))
            self.render_width = self.render_height * 2
            self.src_cam = EquirectangularCamera.from_image_size(
                [self.render_width, self.render_height]
            )

    # ------------------------------------------------------------------
    # Model construction
    # ------------------------------------------------------------------
    def _build_model(self) -> Camera:
        """Builds the target spatialkit Camera from this sensor's parameters."""
        p = self.parameters
        image_size = [self.width, self.height]

        if self.model in _PINHOLE_LIKE:
            if "focal_length" in p and "principal_point" in p:
                cam_dict = {
                    "image_size": image_size,
                    "focal_length": tuple(p["focal_length"]),
                    "principal_point": tuple(p["principal_point"]),
                    "skew": p.get("skew", 0.0),
                    "radial": p.get("radial", [0.0, 0.0, 0.0]),
                    "tangential": p.get("tangential", [0.0, 0.0]),
                }
                return PerspectiveCamera(cam_dict)
            # Derive square-pixel intrinsics from horizontal FOV.
            fx = self.width / (2.0 * math.tan(math.radians(self.hfov) / 2.0))
            cam_dict = {
                "image_size": image_size,
                "focal_length": (fx, fx),
                "principal_point": ((self.width - 1) / 2.0, (self.height - 1) / 2.0),
                "skew": 0.0,
                "radial": p.get("radial", [0.0, 0.0, 0.0]),
                "tangential": p.get("tangential", [0.0, 0.0]),
            }
            return PerspectiveCamera(cam_dict)

        if self.model == "opencv_fisheye":
            return OpenCVFisheyeCamera(
                {
                    "image_size": image_size,
                    "focal_length": tuple(p["focal_length"]),
                    "principal_point": tuple(p["principal_point"]),
                    "skew": p.get("skew", 0.0),
                    "radial": p["radial"],  # [k1,k2,k3,k4]
                }
            )

        if self.model == "thinprism":
            return ThinPrismFisheyeCamera(
                {
                    "image_size": image_size,
                    "focal_length": tuple(p["focal_length"]),
                    "principal_point": tuple(p["principal_point"]),
                    "radial": p["radial"],  # [k1,k2,k3,k4]
                    "tangential": p["tangential"],  # [p1,p2]
                    "prism": p["prism"],  # [sx1,sy1]
                }
            )

        if self.model == "doublesphere":
            return DoubleSphereCamera(
                {
                    "image_size": image_size,
                    "focal_length": tuple(p["focal_length"]),
                    "principal_point": tuple(p["principal_point"]),
                    "xi": p["xi"],
                    "alpha": p["alpha"],
                    "fov_deg": p.get("fov_deg", 180.0),
                }
            )

        if self.model == "omnidirect":
            return OmnidirectionalCamera(
                {
                    "image_size": image_size,
                    "distortion_center": tuple(p["distortion_center"]),
                    "poly_coeffs": p["poly_coeffs"],
                    "inv_poly_coeffs": p["inv_poly_coeffs"],
                    "affine": p.get("affine", [1.0, 0.0, 0.0]),
                    "fov_deg": p.get("fov_deg", 180.0),
                }
            )

        if self.model in ("equirect", "equirectangular"):
            return EquirectangularCamera(
                {
                    "image_size": image_size,
                    "min_phi_deg": p.get("min_phi_deg", -90.0),
                    "max_phi_deg": p.get("max_phi_deg", 90.0),
                }
            )

        raise ValueError(
            f"[CameraSensor:{self.name}] Unsupported camera model '{self.model}'."
        )

    def _precompute_rays(self) -> None:
        """
        Precompute per-pixel ray directions in the **habitat sensor frame** for
        ray casting, plus helpers for depth conversion and validity.

        spatialkit cameras use the CV convention (+Z forward, +X right, +Y down).
        Habitat sensors use the GL convention (-Z forward, +X right, +Y up), so we
        flip Y and Z: R = diag(1, -1, -1).
        """
        rays_cv, valid = self.cam.convert_to_rays(z_fixed=False)  # (3, H*W) unit rays
        rays_hab = rays_cv.copy()
        rays_hab[1, :] *= -1.0  # Y: down -> up
        rays_hab[2, :] *= -1.0  # Z: forward -> -Z

        self._ray_dirs_local = rays_hab.T.astype(np.float64)  # (H*W, 3), habitat frame
        self._ray_valid = np.asarray(valid).reshape(-1)
        # Cosine to optical axis (CV +Z) for planar z-depth conversion.
        self._ray_cos = rays_cv[2, :].astype(np.float64)

    # ------------------------------------------------------------------
    # Quaternion helper (unchanged from the original implementation)
    # ------------------------------------------------------------------
    def _quaternion_to_euler(self, q_xyzw: np.ndarray) -> mn.Vector3:
        """Convert quaternion [x, y, z, w] to Euler (pitch, yaw, roll) radians."""
        x, y, z, w = q_xyzw

        sinr_cosp = 2 * (w * x + y * z)
        cosr_cosp = 1 - 2 * (x * x + y * y)
        roll = math.atan2(sinr_cosp, cosr_cosp)

        sinp = 2 * (w * y - z * x)
        if abs(sinp) >= 1:
            pitch = math.copysign(math.pi / 2, sinp)
        else:
            pitch = math.asin(sinp)

        siny_cosp = 2 * (w * z + x * y)
        cosy_cosp = 1 - 2 * (y * y + z * z)
        yaw = math.atan2(siny_cosp, cosy_cosp)

        return mn.Vector3(pitch, yaw, roll)

    def _rotate_vectors(self, vectors: np.ndarray, q_xyzw: np.ndarray) -> np.ndarray:
        """Vectorized rotation of 3D vectors by a quaternion (same as IdealLiDAR3D)."""
        q_vec = q_xyzw[:3]
        w = q_xyzw[3]
        cross1 = np.cross(q_vec, vectors) + w * vectors
        cross2 = np.cross(q_vec, cross1)
        return vectors + 2.0 * cross2

    # ------------------------------------------------------------------
    # BaseSensor interface
    # ------------------------------------------------------------------
    def is_native(self) -> bool:
        # RGB is rasterized by habitat (directly or via an equirect render source).
        # Depth/Semantic are ray-cast and therefore non-native.
        return self.modality == "rgb"

    def get_sensor_spec(self) -> Optional[habitat_sim.SensorSpec]:
        """SensorSpec for native rendering. Returns None for ray-cast modalities."""
        if self.modality != "rgb":
            return None

        if self.needs_remap:
            # Render a large equirectangular source; get_observation remaps it.
            # Equirectangular requires habitat's dedicated spec class -- a
            # CameraSensorSpec with the EQUIRECTANGULAR subtype is rejected by the
            # simulator ("specification is null").
            spec = habitat_sim.EquirectangularSensorSpec()
            spec.resolution = [self.render_height, self.render_width]
        elif self.model == "equirectangular":
            spec = habitat_sim.EquirectangularSensorSpec()
            spec.resolution = [self.height, self.width]
        else:
            spec = habitat_sim.CameraSensorSpec()
            spec.sensor_subtype = (
                habitat_sim.SensorSubType.ORTHOGRAPHIC
                if self.model == "orthographic"
                else habitat_sim.SensorSubType.PINHOLE
            )
            spec.resolution = [self.height, self.width]
            spec.hfov = mn.Deg(self.hfov)

        spec.uuid = self.name
        spec.sensor_type = habitat_sim.SensorType.COLOR
        spec.position = self.position
        spec.orientation = self.euler
        return spec

    def get_observation(
        self,
        sim: habitat_sim.Simulator,
        motion_state: MotionState,
        tf_manager: Any,
    ) -> Dict[str, Any]:
        """
        Returns ``{self.name: image}``:
        - RGB: rasterized image (native, or remapped from equirect).
        - Depth: float32 (H, W) planar z-depth or euclidean range.
        - Semantic: (H, W) hit object_id.
        """
        if self.modality == "rgb":
            return self._observe_rgb(sim)
        return self._observe_raycast(sim, motion_state)

    # ------------------------------------------------------------------
    # RGB
    # ------------------------------------------------------------------
    def _observe_rgb(self, sim: habitat_sim.Simulator) -> Dict[str, Any]:
        obs = sim.get_sensor_observations()
        if self.name not in obs:
            return {self.name: None}
        image = obs[self.name]
        if not self.needs_remap:
            return {self.name: image}
        # Remap the equirectangular render to the target camera model.
        remapped = transition_camera_view(image, self.src_cam, self.cam)
        return {self.name: remapped}

    # ------------------------------------------------------------------
    # Depth / Semantic (ray casting)
    # ------------------------------------------------------------------
    def _observe_raycast(
        self, sim: habitat_sim.Simulator, motion_state: MotionState
    ) -> Dict[str, Any]:
        H, W = self.height, self.width

        agent_pos = np.asarray(motion_state.position, dtype=np.float64)
        q_agent_xyzw = np.asarray(motion_state.orientation, dtype=np.float64)
        q_agent_mn = mn.Quaternion(
            mn.Vector3(
                float(q_agent_xyzw[0]),
                float(q_agent_xyzw[1]),
                float(q_agent_xyzw[2]),
            ),
            float(q_agent_xyzw[3]),
        )

        # Sensor world position = agent_pos + R(agent) * sensor_offset.
        sensor_pos_local = np.array(
            [self.position.x, self.position.y, self.position.z]
        )
        sensor_pos_global = (
            agent_pos
            + self._rotate_vectors(sensor_pos_local[np.newaxis, :], q_agent_xyzw)[0]
        )

        # Sensor world orientation = R(agent) * R(offset).
        q_sensor_global = q_agent_mn * self.orientation
        q_sensor_global_xyzw = np.array(
            [
                q_sensor_global.vector.x,
                q_sensor_global.vector.y,
                q_sensor_global.vector.z,
                q_sensor_global.scalar,
            ]
        )

        # Rotate all local rays into the world frame at once.
        dirs_global = self._rotate_vectors(self._ray_dirs_local, q_sensor_global_xyzw)

        ray_origin = mn.Vector3(
            sensor_pos_global[0], sensor_pos_global[1], sensor_pos_global[2]
        )

        is_depth = self.modality == "depth"
        if is_depth:
            out = np.zeros((H * W,), dtype=np.float32)
        else:
            out = np.zeros((H * W,), dtype=np.uint32)

        planar = self.depth_type == "planar"
        for idx in range(H * W):
            if not self._ray_valid[idx]:
                continue
            d = dirs_global[idx]
            ray = habitat_sim.geo.Ray(
                ray_origin, mn.Vector3(float(d[0]), float(d[1]), float(d[2]))
            )
            results = sim.cast_ray(ray, max_distance=self.max_distance)
            if not results.has_hits():
                continue
            hit = results.hits[0]
            dist = hit.ray_distance
            if dist < self.min_distance:
                continue
            if is_depth:
                if planar:
                    out[idx] = dist * self._ray_cos[idx]
                else:
                    out[idx] = dist
            else:
                out[idx] = hit.object_id

        return {self.name: out.reshape(H, W)}
