import math
import numpy as np
import habitat_sim
from typing import Dict, Optional

from src.sensors.base_sensor import BaseSensor
from src.datatypes.image import SemanticMap, InstanceMap
from src.datatypes.motion_state import MotionState
from src.detections.obb import global_obbs
from src.detections.bbox2d import boxes_from_maps
from src.detections.bbox3d import obbs_for_visible
from src.sensors.camera import rgb, raycast
from src.sensors.camera.models import Camera, EquirectangularCamera
from src.sensors.camera.model_factory import (
    available_models,
    build_camera_model,
    camera_intrinsic_values,
    model_parameter_keys,
)
from src.sensors.registry import register_sensor
from src.raycasting.types import RaycastResult
from src.utils.geometry import compose_pose


# RGB camera models that habitat-sim can rasterize natively (no remap needed).
_HABITAT_NATIVE_RGB = {"pinhole", "equirectangular", "orthographic"}
# Models treated as a perspective/pinhole pipeline (planar z-depth default).
_PINHOLE_LIKE = {"pinhole", "perspective"}
# Fallback FOV for a native RGB spec with no intrinsic (only the unused
# orthographic model reaches this -- its habitat spec needs a value but has no
# focal length). hfov is never a user input.
_DEFAULT_HFOV = 90.0


def _as_builtin(value: object) -> object:
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, tuple):
        return [_as_builtin(v) for v in value]
    if isinstance(value, list):
        return [_as_builtin(v) for v in value]
    if isinstance(value, dict):
        return {str(k): _as_builtin(v) for k, v in value.items()}
    if isinstance(value, np.generic):
        return value.item()
    return value


@register_sensor("camera")
class CameraSensor(BaseSensor):
    """
    Camera sensor supporting arbitrary projection models for SLAM data generation.

    Design (see project plan):
    - **RGB** keeps habitat-sim's rasterization. ``pinhole``/``equirectangular``/
      ``orthographic`` render natively; any other model is rendered as a large
      equirectangular image and then **remapped** to the target model.
    - **Depth / Semantic** are generated by per-pixel **ray casting**
      (``sim.cast_ray``) through the target camera model's rays, which is more
      accurate than rasterization and works for any (wide-FOV) model.

    The projection math comes from the vendored spatialkit camera models
    (``src/sensors/camera/models``). Camera-specific generation stays inside
    this class; SensorSuite wraps returned output payloads for export.
    """

    def __init__(self, **kwargs) -> None:
        """Read config into the per-capture state this camera needs.

        One linear pass: geometry, then the enabled outputs and their settings,
        the mount pose, and finally the projection ``Camera`` + ray table -- built
        only when an output actually needs them (ray casting, or RGB on a
        non-native model that must be remapped).
        """
        super().__init__(**kwargs)
        p = self.parameters

        # --- Geometry (FOV is derived from the intrinsic, never an input) ---
        self.model = p.get("model", "pinhole").lower()
        self.width = int(p.get("width", 640))
        self.height = int(p.get("height", 480))
        self.min_distance = float(p.get("min_distance", 0.05))
        self.max_distance = float(p.get("max_distance", 100.0))
        self.hfov = self._native_hfov()

        # --- Enabled outputs + their settings (BaseSensor stored self.outputs) ---
        self.modalities = set(self.outputs)
        self._raycast_outputs = self.modalities & {
            "depth", "semantic", "instance", "bbox2d", "bbox3d"
        }
        # Output settings live only in the sensor's ``parameters`` (single source):
        # depth_type: planar z-depth (pinhole) vs euclidean (wide-angle);
        # min_box_px: drop 2D detections smaller than this many pixels.
        default_depth = "planar" if self.model in _PINHOLE_LIKE else "euclidean"
        self.depth_type = str(p.get("depth_type", default_depth)).lower()
        self.min_box_px = int(p.get("min_box_px", 8))

        # --- Mount pose. No silent fallback: an unresolvable parent_link is a
        # config error, not a recoverable one -- masking it here would mount the
        # sensor at identity and produce plausible-looking but wrong ground truth.
        self.pose = self.tf_manager.get_relative_pose("base_link", self.parent_link)

        # --- Projection Camera + ray table, built only if an output needs it ---
        self.cam: Optional[Camera] = None
        self.src_cam: Optional[EquirectangularCamera] = None
        self.needs_remap = False
        self.render_height: Optional[int] = None
        self.render_width: Optional[int] = None
        if self._raycast_outputs:
            self.cam = self._build_camera_model()
            # Ray table (directions/validity/optical-axis cosine) in the habitat
            # sensor frame; cast per capture from the world pose.
            self._ray_dirs_local, self._ray_valid, self._ray_cos = raycast.precompute_rays(self.cam)
        if "rgb" in self.modalities and self.model not in _HABITAT_NATIVE_RGB:
            # Non-native RGB: render a large equirect source, then remap to model.
            self.cam = self.cam or self._build_camera_model()
            self.needs_remap = True
            self.render_height = int(p.get("render_height", 1024))
            self.render_width = self.render_height * 2
            self.src_cam = EquirectangularCamera.from_image_size(
                [self.render_width, self.render_height]
            )

        # Per-instance world OBBs for bbox3d, memoized from the Scene on first use.
        self._world_obbs = None

    def _native_hfov(self) -> float:
        """Horizontal FOV in degrees for habitat's native RGB spec.

        Pinhole/perspective derive it from the intrinsic ``fx``; other native
        models have no intrinsic (only the unused orthographic spec actually
        reads it) and fall back to :data:`_DEFAULT_HFOV`.
        """
        if self.model not in _PINHOLE_LIKE:
            return _DEFAULT_HFOV
        p = self.parameters
        if "intrinsic" in p:
            fx = camera_intrinsic_values(p)[0]
        elif "focal_length" in p:
            fx = float(tuple(p["focal_length"])[0])
        else:
            raise ValueError(
                f"CameraSensor '{self.name}' model '{self.model}' requires an "
                "intrinsic: provide 'intrinsic: [fx, fy, cx, cy]' (or "
                "'focal_length' + 'principal_point')."
            )
        return math.degrees(2.0 * math.atan(self.width / (2.0 * fx)))

    def _build_camera_model(self) -> Camera:
        """Construct this sensor's spatialkit ``Camera`` via the model factory."""
        return build_camera_model(
            self.model,
            self.parameters,
            width=self.width,
            height=self.height,
            sensor_name=self.name,
        )

    @classmethod
    def validate_outputs(cls, outputs: Dict[str, object]) -> None:
        """Validate camera output names from sensor config."""
        allowed = {"rgb", "depth", "semantic", "instance", "bbox2d", "bbox3d"}
        unsupported = sorted(set(outputs) - allowed)
        if unsupported:
            raise ValueError(
                "camera outputs contain unsupported name(s): "
                f"{', '.join(unsupported)}. Available: {', '.join(sorted(allowed))}."
            )

    # Parameter keys read regardless of projection model. The model-specific
    # keys live in the model factory (`MODEL_SPECS`) and are pulled in via
    # `model_parameter_keys` -- a single source shared with construction.
    # (`intrinsic` is pinhole-specific and lives in the model keys, not here;
    # `hfov` is not accepted at all -- it is derived from the intrinsic.)
    _COMMON_PARAMETERS = {
        "model", "width", "height",
        "min_distance", "max_distance", "depth_type", "render_height", "min_box_px",
    }

    @classmethod
    def validate_parameters(cls, parameters: Dict[str, object]) -> None:
        """Reject unknown/invalid camera parameters at config time.

        The allowed key set is model-dependent: common keys plus the extras the
        selected projection model reads (from the model factory). Pinhole-like
        models must carry an intrinsic (no FOV input). Other required-but-missing
        model params are still enforced at construction (``build_camera_model``);
        this catches typos, cross-model leftovers, and a missing intrinsic up
        front.
        """
        model = str(parameters.get("model", "pinhole")).lower()
        if model not in available_models():
            raise ValueError(
                f"camera sensor: unsupported model '{model}'. "
                f"Available: {', '.join(available_models())}."
            )
        allowed = cls._COMMON_PARAMETERS | model_parameter_keys(model)
        cls._reject_unknown_parameters(parameters, allowed, f"camera[{model}]")
        cls._require_positive(
            parameters, ("width", "height", "min_distance", "max_distance"), "camera",
        )
        if model in _PINHOLE_LIKE and not (
            "intrinsic" in parameters
            or ("focal_length" in parameters and "principal_point" in parameters)
        ):
            raise ValueError(
                f"camera[{model}] sensor: requires an intrinsic -- provide "
                "'intrinsic: [fx, fy, cx, cy]' (or 'focal_length' + "
                "'principal_point'). FOV input ('hfov') is not supported."
            )

    def calibration_dict(self) -> Dict[str, object]:
        """Build a sidecar-friendly calibration record for this camera.

        The project supports projection models that do not map cleanly onto
        ROS ``sensor_msgs/CameraInfo`` fields, so calibration is exported as
        structured YAML beside the MCAP rather than as a lossy ROS channel.

        Returns:
            YAML-safe mapping with camera identity, frame, projection model,
            ranges, enabled outputs, and model-specific parameters.
        """
        cam = self.cam
        if cam is None and self.model != "orthographic":
            cam = self._build_camera_model()

        model_data = cam.export_cam_dict() if cam is not None else {
            "cam_type": self.model.upper(),
            "image_size": [self.width, self.height],
        }
        return _as_builtin({
            "name": self.name,
            "frame_id": self.parent_link,
            "model": self.model,
            "width": self.width,
            "height": self.height,
            "hfov": self.hfov,
            "min_distance": self.min_distance,
            "max_distance": self.max_distance,
            "depth_type": self.depth_type,
            "enabled_outputs": sorted(self.modalities),
            "camera_model": model_data,
            "parameters": self.parameters,
        })

    # ------------------------------------------------------------------
    # BaseSensor interface
    # ------------------------------------------------------------------
    def is_native(self) -> bool:
        """Return whether this camera contributes a native Habitat RGB sensor."""
        # RGB is rasterized by habitat (directly or via an equirect render source).
        # Depth/Semantic/Instance are ray-cast and therefore non-native.
        return "rgb" in self.modalities

    def get_sensor_spec(self) -> Optional[habitat_sim.SensorSpec]:
        """SensorSpec for native rendering. Returns None without an RGB output."""
        if "rgb" not in self.modalities:
            return None
        return rgb.native_sensor_spec(
            name=self.name,
            model=self.model,
            needs_remap=self.needs_remap,
            height=self.height,
            width=self.width,
            hfov=self.hfov,
            pose=self.pose,
            render_height=self.render_height,
            render_width=self.render_width,
        )

    def get_observation(
        self,
        sim: habitat_sim.Simulator,
        motion_state: MotionState,
    ) -> Dict[str, object]:
        """Capture the configured camera outputs.

        Args:
            sim: Habitat simulator instance. RGB outputs read the native sensor
                observation from this simulator.
            motion_state: Robot state at the capture timestamp. Ray-cast outputs
                use the pose to place camera rays in world coordinates.

        Returns:
            Mapping of configured output name to payload:
            ``rgb`` -> ``RGBImage``; ``depth`` -> ``DepthMap``;
            ``semantic`` -> ``SemanticMap``; ``instance`` -> ``InstanceMap``;
            ``bbox2d`` -> ``List[Detection2D]``; ``bbox3d`` ->
            ``Dict[str, List[OBB3D]]``.
        """
        outputs: Dict[str, object] = {}
        if "rgb" in self.modalities:
            outputs["rgb"] = rgb.observe(
                sim,
                name=self.name,
                needs_remap=self.needs_remap,
                src_cam=self.src_cam,
                cam=self.cam,
            )
        if self._raycast_outputs:
            outputs.update(self._observe_raycast(sim, motion_state))
        return outputs

    # ------------------------------------------------------------------
    # Ray casting (depth / semantic / instance, and reused by detections)
    # ------------------------------------------------------------------
    def world_pose(self, motion_state: MotionState) -> tuple[np.ndarray, np.ndarray]:
        """Compute this camera's world pose at ``motion_state``.

        position = agent_pos + R(agent) * mount_offset; orientation = R(agent) * R(offset).

        Args:
            motion_state: Robot state that owns the base pose.

        Returns:
            Tuple ``(position_xyz, quat_xyzw)`` in Habitat world coordinates.
        """
        agent_pos = np.asarray(motion_state.position, dtype=np.float64)
        q_agent_xyzw = np.asarray(motion_state.orientation, dtype=np.float64)
        sensor_pos_global, q_sensor_global_xyzw = compose_pose(
            agent_pos,
            q_agent_xyzw,
            self.pose.position,
            self.pose.orientation,
        )
        return sensor_pos_global, q_sensor_global_xyzw

    def _cast(
        self, sim: habitat_sim.Simulator, motion_state: MotionState
    ) -> tuple[RaycastResult, np.ndarray]:
        """Ray-cast the scene from this camera.

        Args:
            sim: Habitat simulator instance, used only for fallback scene
                extraction paths.
            motion_state: Robot state used to compute the camera world pose.

        Returns:
            Tuple of batched raycast result and flat valid-hit mask of shape
            ``(height * width,)``.
        """
        if self.scene is None:
            raise RuntimeError("Camera raycast outputs require a Scene; no sim.cast_ray fallback is created.")

        # The Scene is bound/synced once per capture by SensorSuite.observe;
        # the backend raises if queried unbound.
        world_pos, world_quat = self.world_pose(motion_state)
        return raycast.cast(
            self.scene,
            ray_dirs_local=self._ray_dirs_local,
            ray_valid=self._ray_valid,
            world_pos=world_pos,
            world_quat=world_quat,
            min_distance=self.min_distance,
            max_distance=self.max_distance,
        )

    def cast_ids(
        self, sim: habitat_sim.Simulator, motion_state: MotionState
    ) -> tuple[InstanceMap, SemanticMap]:
        """Cast camera rays and return instance and semantic id maps.

        Args:
            sim: Habitat simulator instance.
            motion_state: Robot state used to compute the camera world pose.

        Returns:
            Tuple ``(instance_map, semantic_map)``; both are ``(H, W)`` uint32
            arrays with ``0`` for no hit.
        """
        res, hit = self._cast(sim, motion_state)
        return raycast.id_maps(res, hit, self.height, self.width)

    def _ensure_detection_context(self, sim: habitat_sim.Simulator) -> None:
        categories = self.scene.categories
        if categories is None:
            raise RuntimeError(
                f"Camera '{self.name}' produces detections but the shared Scene "
                "has no category table; it must be bound to the sim (e.g. by "
                "create_simulator) before capture."
            )
        if self._world_obbs is None and "bbox3d" in self.modalities:
            # Reuse the SceneModel the Scene already built in bind() (item 5);
            # only extract from scratch for backends that hold no model (e.g. sim).
            scene_model = self.scene.model
            if scene_model is None:
                from src.raycasting import extract_scene_model

                scene_model = extract_scene_model(sim, self.scene.geometry)
            self._world_obbs = global_obbs(scene_model, categories)

    def _observe_raycast(
        self, sim: habitat_sim.Simulator, motion_state: MotionState
    ) -> Dict[str, object]:
        """Cast once and derive every configured ray-cast output from it."""
        H, W = self.height, self.width
        res, hit = self._cast(sim, motion_state)
        outputs: Dict[str, object] = {}

        # Instance/semantic maps are shared by the map outputs and detections;
        # build them once when any of those outputs is configured.
        inst = sem = None
        if self.modalities & {"semantic", "instance", "bbox2d", "bbox3d"}:
            inst, sem = raycast.id_maps(res, hit, H, W)

        if "depth" in self.modalities:
            outputs["depth"] = raycast.depth_map(
                res, hit, self._ray_cos, self.depth_type, H, W
            )
        if "semantic" in self.modalities:
            outputs["semantic"] = sem
        if "instance" in self.modalities:
            outputs["instance"] = inst

        if "bbox2d" in self.modalities:
            self._ensure_detection_context(sim)
            outputs["bbox2d"] = boxes_from_maps(
                inst, sem, self.scene.categories, self.min_box_px
            )
        if "bbox3d" in self.modalities:
            self._ensure_detection_context(sim)
            cam_pos, cam_quat = self.world_pose(motion_state)
            outputs["bbox3d"] = obbs_for_visible(
                inst, self._world_obbs, cam_pos, cam_quat
            )

        return outputs
